export const SET_LANGUAGE = "SET_LANGUAGE"; // 设置语言
export const SET_THEME = "SET_THEME"; // 设置黑白主题
export const SET_THEME_TYPE = "SET_THEME_TYPE"; // 设置主题颜色类型
export const SET_SHOW_BIG_PLAYER = "SET_SHOW_BIG_PLAYER";
export const SET_USER_DATA = "SET_USER_DATA"; // 设置用户信息
export const SET_THEME_DATA = "SET_THEME_DATA"; // 设置主题配色
export const SET_USER_LOGIN = "SET_USER_LOGIN"; // 设置用户登录状态
export const SET_SEARCH_INPUT_ACTIVE = "SET_SEARCH_INPUT_ACTIVE"; // 设置用户登录状态
export const SET_SEARCH_HISTORY = "SET_SEARCH_HISTORY"; // 设置搜索历史
export const SET_SITE_TITLE = "SET_SITE_TITLE"; // 设置搜索历史
